; PlatformIO Project Configuration File
; Automated conversion for esp32-cam-trap-v2

[platformio]
src_dir = .
default_envs = esp32_cam_trap_v2

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    Wire
    SPI

[env:esp32_cam_trap_v2]
build_src_filter = +<esp32_cam_trap_v2/> -<*>
lib_deps =
    ${env.lib_deps}
    witnessmenow/UniversalTelegramBot
